name: rise-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - pytorch
  - xgboost
  - pip
  - ipykernel
  - pip:
      - yfinance